apps:
  prod:
    source: /home/gray/src/fanyou/haizeimao/islandServer
    user: root
    host: 66.112.215.31
    dest: ~/test/haizeimao
    exclude:
      - .git
      - .DS_Store
      - trunk/test
    commands:
      - cd ~/test/haizeimao/islandServer/trunk
      - ls -l
